services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: carfactory-employees-mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/${DB_PORT}' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - carfactory-employees-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carfactory-employees-api
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:${API_PORT}
      - ConnectionStrings__SQLSERVER=Server=mssql,${DB_PORT};Database=${DB_NAME};User Id=sa;Password=${DB_PASSWORD};Trust Server Certificate=true;
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      mssql:
        condition: service_healthy  
    networks:
      - carfactory-employees-network

networks:
  carfactory-employees-network:
    driver: bridge
